default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: hilario1
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sismos_api_development
  username: postgres
  password: hilario1

test:
  <<: *default
  database: sismos_api_test
  username: postgres
  password: hilario1

production:
  <<: *default
  database: sismos_api_production
  username: postgres
  password: hilario1
