
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: hilario1
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sismos_api_development

test:
  <<: *default
  database: sismos_api_test
  username: <%= ENV['POSTGRES_USER']  %>
  password: <%= ENV['POSTGRES_PASSWORD']  %>

production:
  <<: *default
  database: sismos_api_production
  username: <%= ENV['POSTGRES_USER']  %>
  password: <%= ENV['POSTGRES_PASSWORD']  %>
